on:
  push:

jobs:
  # test virtualenv setup on raw debian image
  test-venv:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
    - uses: actions/checkout@v3
    - name: test initial install
      run: |
        ./setup.sh
        .venv/bin/python -c "import viam"
    - name: test reinstall case
      run: |
        ./setup.sh
        .venv/bin/python -c "import viam"
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install
      run: pip install ruff
    - name: lint
      run: ruff check src
